# Generated by Django 5.0 on 2026-08-25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributedLock',
            fields=[
                ('lock_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('holder_id', models.CharField(max_length=255)),
                ('acquired_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'distributed_locks',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255)),
                ('pid', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('SHUTTING_DOWN', 'Shutting Down'), ('DEAD', 'Dead / Unresponsive')], default='ACTIVE', max_length=20)),
                ('concurrency', models.PositiveIntegerField(default=4)),
                ('current_running_jobs', models.PositiveIntegerField(default=0)),
                ('total_processed_jobs', models.PositiveIntegerField(default=0)),
                ('total_failed_jobs', models.PositiveIntegerField(default=0)),
                ('cpu_usage_pct', models.FloatField(default=0.0)),
                ('memory_usage_mb', models.FloatField(default=0.0)),
                ('queues_subscribed', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'workers',
                'ordering': ['-last_heartbeat_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.organization')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['name'],
                'unique_together': {('organization', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('key_prefix', models.CharField(db_index=True, max_length=16)),
                ('key_hash', models.CharField(db_index=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='core.project')),
            ],
            options={
                'db_table': 'api_keys',
            },
        ),
        migrations.CreateModel(
            name='RetryPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('strategy', models.CharField(choices=[('FIXED', 'Fixed Delay'), ('LINEAR_BACKOFF', 'Linear Backoff'), ('EXPONENTIAL_BACKOFF', 'Exponential Backoff')], default='EXPONENTIAL_BACKOFF', max_length=30)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('initial_interval_seconds', models.PositiveIntegerField(default=5)),
                ('max_interval_seconds', models.PositiveIntegerField(default=3600)),
                ('backoff_multiplier', models.FloatField(default=2.0)),
                ('jitter', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retry_policies', to='core.project')),
            ],
            options={
                'db_table': 'retry_policies',
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('priority', models.PositiveIntegerField(default=10, help_text='Higher value = higher processing priority (1-100)')),
                ('concurrency_limit', models.PositiveIntegerField(default=10, help_text='Max concurrent running jobs across worker fleet')),
                ('rate_limit_per_second', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('burst_limit', models.PositiveIntegerField(default=0)),
                ('is_paused', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='core.project')),
                ('default_retry_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.retrypolicy')),
            ],
            options={
                'db_table': 'queues',
                'ordering': ['-priority', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RateLimitBucket',
            fields=[
                ('queue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rate_limit_bucket', serialize=False, to='core.queue')),
                ('tokens', models.FloatField(default=0.0)),
                ('last_refill_timestamp', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'rate_limit_buckets',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('DELAYED', 'Delayed'), ('SCHEDULED', 'Scheduled'), ('RECURRING', 'Recurring (Cron)'), ('BATCH', 'Batch Parent'), ('BATCH_CHILD', 'Batch Child'), ('WORKFLOW_STEP', 'Workflow Step (DAG)')], default='IMMEDIATE', max_length=30)),
                ('handler', models.CharField(default='mock_task', help_text='Registered execution handler function', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending (Dependencies Unmet)'), ('QUEUED', 'Queued'), ('CLAIMED', 'Claimed by Worker'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('DEAD_LETTER', 'Dead Letter'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', max_length=20)),
                ('priority', models.PositiveIntegerField(default=10)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_stack', models.TextField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('scheduled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('timeout_seconds', models.PositiveIntegerField(default=300)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('current_attempt', models.PositiveIntegerField(default=0)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('batch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_jobs', to='core.job')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.project')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.queue')),
                ('retry_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.retrypolicy')),
                ('claimed_by_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_jobs', to='core.worker')),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeadLetterQueueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
                ('failure_reason', models.TextField()),
                ('failure_category', models.CharField(choices=[('TIMEOUT', 'Execution Timeout'), ('CRASH', 'Process Crash / OOM'), ('EXCEPTION', 'Unhandled Exception'), ('RATE_LIMIT', 'Rate Limit Exceeded'), ('DEPENDENCY_FAILED', 'Parent Dependency Failed'), ('UNHANDLED', 'Other Failure')], default='EXCEPTION', max_length=30)),
                ('ai_summary', models.TextField(blank=True, default='', help_text='AI-generated failure root-cause analysis')),
                ('replayed_at', models.DateTimeField(blank=True, null=True)),
                ('replay_count', models.PositiveIntegerField(default=0)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dlq_entry', to='core.job')),
                ('original_queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlq_entries', to='core.queue')),
            ],
            options={
                'db_table': 'dead_letter_queue_entries',
                'ordering': ['-failed_at'],
            },
        ),
        migrations.CreateModel(
            name='JobExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('TIMED_OUT', 'Timed Out'), ('CANCELLED', 'Cancelled')], default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('exit_code', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('error_stack', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='core.job')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='core.worker')),
            ],
            options={
                'db_table': 'job_executions',
                'ordering': ['attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warning'), ('ERROR', 'Error'), ('DEBUG', 'Debug')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.jobexecution')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.job')),
            ],
            options={
                'db_table': 'job_logs',
                'ordering': ['timestamp', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('handler', models.CharField(default='mock_task', max_length=255)),
                ('cron_expression', models.CharField(help_text='Standard 5-part cron syntax e.g. */10 * * * *', max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('priority', models.PositiveIntegerField(default=10)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_jobs', to='core.project')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_jobs', to='core.queue')),
            ],
            options={
                'db_table': 'scheduled_jobs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('running_job_count', models.PositiveIntegerField(default=0)),
                ('completed_job_count', models.PositiveIntegerField(default=0)),
                ('failed_job_count', models.PositiveIntegerField(default=0)),
                ('cpu_usage_pct', models.FloatField(default=0.0)),
                ('memory_usage_mb', models.FloatField(default=0.0)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='core.worker')),
            ],
            options={
                'db_table': 'worker_heartbeats',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='JobDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_status', models.CharField(default='COMPLETED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='core.job')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='core.job')),
            ],
            options={
                'db_table': 'job_dependencies',
                'unique_together': {('job', 'depends_on')},
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('DEVELOPER', 'Developer'), ('VIEWER', 'Viewer')], default='DEVELOPER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_memberships',
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['queue', 'status', '-priority', 'scheduled_at'], name='job_claim_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['project', 'status'], name='job_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'scheduled_at'], name='job_status_sched_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['batch_id'], name='job_batch_idx'),
        ),
    ]

